# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmmm', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Text',
            new_name='text',
        ),
    ]
